[package]
name = "flipduel-escrow"
version = "0.1.0"
description = "Flipduel 1v1 escrow"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "flipduel_escrow"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
